version: '2'
services:
  envoy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    expose:
      - "8001"
    ports:
      - "8001:8001"
    networks:
      - envoymesh
  # envoy:
  #   image: "ubuntu:bionic"
  #   volumes:
  #     - "./service-envoy.yaml:/etc/service-envoy.yaml"
  #   expose:
  #     - "8001"
  #   ports:
  #     - "8001:8001"
  #   networks:
  #     - envoymesh
  #   entrypoint: "/usr/bin/tail -f /dev/null"

  flask-echo:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./service-envoy.yaml:/tmp/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - flask-echo
    expose:
      - "5000"
    ports:
      - "5000:5000"

networks:
  envoymesh: {}
